global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["localhost:3100"]

  - job_name: "sahabatkebaikan-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.56.3:8889"]
