apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://localhost:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://localhost:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      derivedFields:
        - datasourceUid: sahabatkebaikan-backend
          matcherRegex: (?:traceID|trace_id)=(\w+)
          name: TraceID
          url: $${__value.raw}
